name: Build and Deploy
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: world # <-- CHANGE THIS to your subfolder name
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build
        run: |
          npm install
          npx ng build --configuration production --base-href /${{ github.event.repository.name }}/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: YOUR_FOLDER_NAME/dist/*/browser # <-- ALSO CHANGE YOUR_FOLDER_NAME HERE
          branch: gh-pages
